-- Admin
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'student01@csatmaker.site', '$2b$12$9c1Pr1MHU6YGXCrfme3Rxe9FM8WytwATrN.EtL2e6RGcGZz6vdf5S', 0,'Admin');
INSERT INTO BOOK(EMAIL) VALUES ('student01@csatmaker.site');

-- Admin2
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'student02@csatmaker.site', '$2b$12$9c1Pr1MHU6YGXCrfme3Rxe9FM8WytwATrN.EtL2e6RGcGZz6vdf5S', 0,'Admin2');
INSERT INTO BOOK(EMAIL) VALUES ('student02@csatmaker.site');

-- Admin3
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'student03@csatmaker.site', '$2b$12$9c1Pr1MHU6YGXCrfme3Rxe9FM8WytwATrN.EtL2e6RGcGZz6vdf5S', 0,'Admin3');
INSERT INTO BOOK(EMAIL) VALUES ('student03@csatmaker.site');

-- Admin4
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'student04@csatmaker.site', '$2b$12$9c1Pr1MHU6YGXCrfme3Rxe9FM8WytwATrN.EtL2e6RGcGZz6vdf5S', 0,'Admin4');
INSERT INTO BOOK(EMAIL) VALUES ('student04@csatmaker.site');

-- Admin5
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'student05@csatmaker.site', '$2b$12$9c1Pr1MHU6YGXCrfme3Rxe9FM8WytwATrN.EtL2e6RGcGZz6vdf5S', 0,'Admin5');
INSERT INTO BOOK(EMAIL) VALUES ('student05@csatmaker.site');

-- 지도교수
INSERT INTO MEMBER(CREATED_DATE, EMAIL, MEMBER_PW, ROLE, USERNAME) VALUES (CURRENT_TIMESTAMP, 'ejung@hongik.ac.kr', '$2a$10$8Fsj6GzBZPo.9FlH1tAug.3gOljelRAWNpVAGu8koYjOIoydh39aO', 0,'지도교수');
INSERT INTO BOOK(EMAIL) VALUES ('ejung@hongik.ac.kr');